pr:
  branches:
    include:
      - 'develop'

stages:
  - stage: Dev
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self
          - task: NodeTool@0
            inputs:
              versionSpec: '14.x'
            displayName: 'Install Node.js'
          - script: |
              curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
              sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
              sudo apt-get update && sudo apt-get install terraform
            displayName: 'Install Terraform'
          - script: |
              chmod +x ./infrastructure/deploy.sh
              ./infrastructure/deploy.sh dev
            displayName: 'Deploy to Dev'
          - script: |
              cd ./test
              npm install
              npm run test:dev
            displayName: 'Run Dev infrastructure tests'
          - script: |
              chmod +x ./infrastructure/destroy.sh
              ./infrastructure/destroy.sh dev
            displayName: 'Destroy Dev'
  - stage: QA
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self
          - task: NodeTool@0
            inputs:
              versionSpec: '14.x'
            displayName: 'Install Node.js'
          - script: |
              curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
              sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
              sudo apt-get update && sudo apt-get install terraform
            displayName: 'Install Terraform'
          - script: |
              chmod +x ./infrastructure/deploy.sh
              ./infrastructure/deploy.sh qa
            displayName: 'Deploy to QA'
          - script: |
              cd ./test
              npm install
              npm run test:qa
            displayName: 'Run QA infrastructure tests'
          - script: |
              chmod +x ./infrastructure/destroy.sh
              ./infrastructure/destroy.sh qa
            displayName: 'Destroy QA'
